# Generated by Django 5.2.1 on 2025-07-16 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0019_remove_sancionempleado_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rostro',
            fields=[
                ('id_empl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='empleados.empleado')),
                ('encoding', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
        ),
    ]
