# Generated by Django 5.2.1 on 2025-09-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='minutos_retraso',
            field=models.IntegerField(default=0),
        ),
    ]
