# Generated by Django 5.2.1 on 2025-10-16 00:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_asistencia_minutos_retraso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
