# Generated by Django 5.2.1 on 2025-05-29 18:50

import empleados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(validators=[empleados.models.validar_mayor_18]),
        ),
    ]
