# Generated by Django 5.2.1 on 2025-06-04 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo_Sueldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('periodo', models.CharField(max_length=7)),
                ('ruta_pdf', models.FileField(upload_to='recibos/pdf/')),
                ('ruta_imagen', models.ImageField(blank=True, null=True, upload_to='recibos/imagenes/')),
                ('id_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='empleados.empleado')),
            ],
            options={
                'unique_together': {('id_empl', 'periodo')},
            },
        ),
    ]
