# Generated by Django 5.2.1 on 2025-06-04 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_recibo_sueldos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recibo_sueldos',
            unique_together=set(),
        ),
    ]
