# Generated by Django 5.2.1 on 2025-06-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_recibo_sueldos_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ruta_foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/fotos/'),
        ),
    ]
