# Generated by Django 5.2.1 on 2025-06-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_alter_empleado_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo_sueldos',
            old_name='id_empl',
            new_name='id_emple',
        ),
    ]
