# Generated by Django 5.2.1 on 2025-06-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_rename_id_empl_recibo_sueldos_id_emple'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo_sueldos',
            old_name='id_emple',
            new_name='id_empl',
        ),
    ]
