# Generated by Django 5.2.1 on 2025-06-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_rename_id_emple_recibo_sueldos_id_empl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='hora_entrada',
            field=models.TimeField(choices=[('09:00', '09:00'), ('14:00', '14:00')]),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='hora_salida',
            field=models.TimeField(choices=[('13:00', '13:00'), ('18:00', '18:00')]),
        ),
    ]
