# Generated by Django 5.2.1 on 2025-06-24 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0010_alter_horarios_hora_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='hora_entrada',
            field=models.TimeField(choices=[(datetime.time(9, 0), '09:00'), (datetime.time(14, 0), '14:00')]),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='hora_salida',
            field=models.TimeField(choices=[(datetime.time(13, 0), '13:00'), (datetime.time(18, 0), '18:00')]),
        ),
    ]
