# Generated by Django 5.2.1 on 2025-06-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_alter_horarios_hora_entrada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacionhorario',
            old_name='empleado',
            new_name='id_empl',
        ),
        migrations.RenameField(
            model_name='asignacionhorario',
            old_name='horario',
            new_name='id_horario',
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='id_empl',
        ),
    ]
