# Generated by Django 5.2.1 on 2025-07-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0012_rename_empleado_asignacionhorario_id_empl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doc', models.CharField(max_length=100)),
                ('estado_doc', models.BooleanField(default=True)),
                ('obligatorio', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Legajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_leg', models.CharField(max_length=50)),
                ('fecha_creacion_leg', models.DateField(auto_now_add=True)),
                ('nro_leg', models.IntegerField(unique=True)),
                ('fecha_modificacion_leg', models.DateField(auto_now=True)),
                ('id_empl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legajo', to='empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_archivo', models.FileField(upload_to='legajos/documentos/')),
                ('fecha_hora_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_doc', models.BooleanField(default=True)),
                ('id_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.legajo')),
                ('id_requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.requisitodocumento')),
            ],
        ),
    ]
