# Generated by Django 5.2.1 on 2025-07-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0014_resolucion_sancion_sancionempleadoresolucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sancionempleadoresolucion',
            name='id_resolucion',
        ),
        migrations.RemoveField(
            model_name='sancionempleadoresolucion',
            name='id_sancion',
        ),
        migrations.RemoveField(
            model_name='sancionempleadoresolucion',
            name='id_empl',
        ),
        migrations.DeleteModel(
            name='Resolucion',
        ),
        migrations.DeleteModel(
            name='Sancion',
        ),
        migrations.DeleteModel(
            name='SancionEmpleadoResolucion',
        ),
    ]
