# Generated by Django 5.2.1 on 2025-07-09 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0015_remove_sancionempleadoresolucion_id_resolucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_incid', models.DateField()),
                ('descripcion_incid', models.CharField(max_length=255)),
                ('nombre_incid', models.CharField(max_length=255)),
                ('tipo_incid', models.CharField(max_length=255)),
                ('estado_incid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidenteEmpleadoDescargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ocurrencia', models.DateField()),
                ('observaciones', models.CharField(max_length=255)),
                ('responsable_registro', models.CharField(max_length=255)),
                ('estado', models.BooleanField()),
                ('id_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('id_incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.incidente')),
            ],
            options={
                'unique_together': {('id_incidente', 'id_empl')},
            },
        ),
        migrations.CreateModel(
            name='Descargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descargo', models.DateField()),
                ('contenido_descargo', models.CharField(max_length=255)),
                ('ruta_archivo_descargo', models.CharField(max_length=255)),
                ('estado_descargo', models.BooleanField()),
                ('id_incid_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.incidenteempleadodescargo')),
            ],
        ),
        migrations.CreateModel(
            name='SancionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('id_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones_empleado', to='empleados.empleado')),
                ('id_sancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.sancion')),
            ],
            options={
                'verbose_name': 'Sanción de Empleado',
                'verbose_name_plural': 'Sanciones de Empleados',
                'unique_together': {('id_empl', 'id_sancion', 'fecha_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resolucion', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('sancion_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones', to='empleados.sancionempleado')),
            ],
        ),
    ]
