# Generated by Django 5.2.1 on 2025-07-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0016_incidente_sancion_incidenteempleadodescargo_descargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionhorario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='descargo',
            name='estado_descargo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='estado_incid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='incidenteempleadodescargo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
