# Generated by Django 5.2.1 on 2025-07-10 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0017_alter_asignacionhorario_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sancionempleado',
            name='incidente_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones_generadas', to='empleados.incidenteempleadodescargo'),
        ),
    ]
