# Generated by Django 5.2.1 on 2025-07-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0018_sancionempleado_incidente_asociado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sancionempleado',
            name='estado',
        ),
    ]
