# Generated by Django 5.2.1 on 2025-08-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0019_remove_sancionempleado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sancionempleado',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
