# Generated by Django 5.2.1 on 2025-08-27 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0020_sancionempleado_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sancionempleado',
            name='estado',
        ),
    ]
