# Generated by Django 5.2.1 on 2025-08-28 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0021_remove_sancionempleado_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(help_text='El contenido de la notificación.')),
                ('leida', models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la notificación.')),
                ('enlace', models.CharField(blank=True, help_text='URL a la que se redirigirá al hacer clic. Puede ser una URL absoluta o una ruta relativa de Django.', max_length=255, null=True)),
                ('id_empl', models.ForeignKey(help_text='Empleado que recibirá la notificación.', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
