# Generated by Django 5.2.1 on 2025-08-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0022_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
