# Generated by Django 5.2.1 on 2025-09-11 01:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0024_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descargo',
            name='id_incid_empl',
        ),
        migrations.RemoveField(
            model_name='sancionempleado',
            name='incidente_asociado',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='fecha_incid',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='nombre_incid',
        ),
        migrations.RemoveField(
            model_name='resolucion',
            name='sancion_empleado',
        ),
        migrations.RemoveField(
            model_name='sancion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='sancionempleado',
            name='fecha_sancion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IncidenteEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ocurrencia', models.DateField(auto_now=True)),
                ('observaciones', models.CharField(max_length=255)),
                ('responsable_registro', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('id_descargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.descargo')),
                ('id_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('id_incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.incidente')),
                ('id_resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.resolucion')),
            ],
            options={
                'unique_together': {('id_incidente', 'id_empl')},
            },
        ),
        migrations.DeleteModel(
            name='IncidenteEmpleadoDescargo',
        ),
    ]
