# Generated by Django 5.2.1 on 2025-09-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0025_remove_descargo_id_incid_empl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenteempleado',
            name='fecha_ocurrencia',
            field=models.DateField(),
        ),
    ]
