# Generated by Django 5.2.1 on 2025-09-19 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0026_alter_incidenteempleado_fecha_ocurrencia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sancionempleado',
            unique_together=set(),
        ),
    ]
