# Generated by Django 5.2.1 on 2025-09-18 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0026_alter_incidenteempleado_fecha_ocurrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sancionempleado',
            name='incidente_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones', to='empleados.incidenteempleado'),
        ),
    ]
