# Generated by Django 5.2.1 on 2025-09-19 23:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0027_sancionempleado_incidente_asociado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='cantidad_personal',
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='turno',
        ),
        migrations.AddField(
            model_name='horarios',
            name='cantidad_personal_requerida',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad de Personal Requerida'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horarios',
            name='jueves',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='lunes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='martes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='miercoles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horarios',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horarios',
            name='viernes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asignacionhorario',
            name='id_empl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_horario', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='asignacionhorario',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='empleados.horarios'),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='hora_entrada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='hora_salida',
            field=models.TimeField(),
        ),
    ]
