# Generated by Django 5.2.1 on 2025-09-20 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0027_alter_sancionempleado_unique_together'),
        ('empleados', '0028_remove_horarios_cantidad_personal_and_more'),
    ]

    operations = [
    ]
