# Generated by Django 5.2.1 on 2025-09-22 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0029_merge_20250919_2133'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(help_text='Nombre de la tabla afectada.', max_length=64)),
                ('registro_id', models.IntegerField(blank=True, help_text='Clave primaria (ID) del registro afectado.', null=True)),
                ('accion', models.CharField(choices=[('INSERT', 'Inserción'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], help_text='Acción realizada sobre el registro (INSERT, UPDATE, DELETE).', max_length=6)),
                ('datos', models.JSONField(blank=True, help_text='Datos del registro en formato JSON (ej. estado anterior o posterior).', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el evento.')),
                ('actor', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'auditoria',
                'ordering': ['-creado_en'],
            },
        ),
    ]
