# Generated by Django 5.2.1 on 2025-09-22 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0030_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenteempleado',
            name='incidente_anterior',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidente_siguiente', to='empleados.incidenteempleado'),
        ),
        migrations.AlterField(
            model_name='incidenteempleado',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('CORREGIDO', 'Corregido')], default='ABIERTO', max_length=20),
        ),
    ]
