# Generated by Django 5.2.1 on 2025-10-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0028_merge_20250919_2129'),
        ('empleados', '0031_incidenteempleado_incidente_anterior_and_more'),
    ]

    operations = [
    ]
