# Generated by Django 5.2.1 on 2025-10-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0032_merge_20251006_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descargo',
            name='ruta_archivo_descargo',
            field=models.FileField(blank=True, null=True, upload_to='descargos/'),
        ),
    ]
