# Generated by Django 5.2.1 on 2025-10-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0033_alter_descargo_ruta_archivo_descargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
