# Generated by Django 5.2.1 on 2025-10-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0033_alter_descargo_ruta_archivo_descargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='grupo',
            field=models.CharField(blank=True, choices=[('TECNICO', 'Técnico'), ('OBRERO', 'Obrero')], max_length=50, null=True, verbose_name='Grupo'),
        ),
    ]
