# Generated by Django 5.2.1 on 2025-10-22 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0034_empleado_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='cargo',
        ),
    ]
